#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Pod-Strip
Version  : 1.100
Release  : 20
URL      : https://cpan.metacpan.org/authors/id/D/DO/DOMM/Pod-Strip-1.100.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DO/DOMM/Pod-Strip-1.100.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libpod-strip-perl/libpod-strip-perl_1.02-2.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Pod-Strip-license = %{version}-%{release}
Requires: perl-Pod-Strip-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
# NAME
Pod::Strip - Remove POD from Perl code
# VERSION
version 1.100
# SYNOPSIS

%package dev
Summary: dev components for the perl-Pod-Strip package.
Group: Development
Provides: perl-Pod-Strip-devel = %{version}-%{release}
Requires: perl-Pod-Strip = %{version}-%{release}

%description dev
dev components for the perl-Pod-Strip package.


%package license
Summary: license components for the perl-Pod-Strip package.
Group: Default

%description license
license components for the perl-Pod-Strip package.


%package perl
Summary: perl components for the perl-Pod-Strip package.
Group: Default
Requires: perl-Pod-Strip = %{version}-%{release}

%description perl
perl components for the perl-Pod-Strip package.


%prep
%setup -q -n Pod-Strip-1.100
cd %{_builddir}
tar xf %{_sourcedir}/libpod-strip-perl_1.02-2.debian.tar.xz
cd %{_builddir}/Pod-Strip-1.100
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Pod-Strip-1.100/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Pod-Strip
cp %{_builddir}/Pod-Strip-1.100/LICENSE %{buildroot}/usr/share/package-licenses/perl-Pod-Strip/9101f7db7b2a1098eca2dce7234116943c939328
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Pod-Strip/ee672cd407ca85488561241114a203da313d6f7e
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Pod::Strip.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Pod-Strip/9101f7db7b2a1098eca2dce7234116943c939328
/usr/share/package-licenses/perl-Pod-Strip/ee672cd407ca85488561241114a203da313d6f7e

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Pod/Strip.pm
